-- ═══════════════════════════════════════════════════════════════
-- Yoca — Supabase database schema (Postgres)
-- Run in the Supabase SQL Editor. Includes tables, RLS policies
-- and default seed rows.
-- ═══════════════════════════════════════════════════════════════

-- ── sections: homepage/section visibility switches ─────────────
create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sections_touch on public.sections;
create trigger trg_sections_touch
  before update on public.sections
  for each row execute function public.touch_updated_at();

-- ── menus: dynamic header/footer navigation ────────────────────
create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  location text not null check (location in ('header', 'footer')),
  order_index integer not null default 0,
  is_active boolean not null default true
);

create index if not exists idx_menus_location on public.menus (location, order_index);

-- ── team_members: about/team showcase ──────────────────────────
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  image_url text,
  linkedin text,
  tags text[] default '{}',
  order_index integer not null default 0,
  is_active boolean not null default true
);

create index if not exists idx_team_order on public.team_members (order_index);

-- ── checkup_submissions: Digital Check-Up leads ────────────────
create table if not exists public.checkup_submissions (
  id uuid primary key default gen_random_uuid(),
  data_json jsonb not null default '{}'::jsonb,
  contact_info_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_checkup_created on public.checkup_submissions (created_at desc);

-- ── contact_submissions: contact form leads ────────────────────
create table if not exists public.contact_submissions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  company text not null default '',
  message text not null default '',
  locale text not null default 'en',
  created_at timestamptz not null default now()
);

create index if not exists idx_contact_created on public.contact_submissions (created_at desc);

-- ── case_studies: Work portfolio (admin-managed, localized JSONB) ──
create table if not exists public.case_studies (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  year text not null default '',
  market text not null default '',
  image_url text not null default '',
  services text[] default '{}',
  order_index integer not null default 0,
  is_active boolean not null default true,
  -- {"en": {name, sector, summary, problem, approach, solution, results}, "tr": {...}, "az": {...}}
  content jsonb not null default '{}'::jsonb
);

create index if not exists idx_case_studies_order on public.case_studies (order_index);

-- ── site_content: admin-editable copy overrides (per locale) ───────
create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text not null,
  locale text not null check (locale in ('en', 'tr', 'az')),
  value text not null default '',
  unique (key, locale)
);

-- ═══ Row Level Security ════════════════════════════════════════
alter table public.sections enable row level security;
alter table public.menus enable row level security;
alter table public.team_members enable row level security;
alter table public.checkup_submissions enable row level security;
alter table public.contact_submissions enable row level security;

-- Public (anon) read access for content tables
drop policy if exists "public read sections" on public.sections;
create policy "public read sections"
  on public.sections for select
  to anon, authenticated
  using (true);

drop policy if exists "public read menus" on public.menus;
create policy "public read menus"
  on public.menus for select
  to anon, authenticated
  using (true);

drop policy if exists "public read team" on public.team_members;
create policy "public read team"
  on public.team_members for select
  to anon, authenticated
  using (true);

-- Check-up submissions: anonymous INSERT only (no read-back).
-- The admin reads them via the Supabase dashboard or service-role key.
drop policy if exists "anon insert checkup" on public.checkup_submissions;
create policy "anon insert checkup"
  on public.checkup_submissions for insert
  to anon, authenticated
  with check (true);

-- Content management (Supabase Studio / service role bypasses RLS,
-- authenticated dashboard users get full control):
drop policy if exists "auth manage sections" on public.sections;
create policy "auth manage sections"
  on public.sections for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth manage menus" on public.menus;
create policy "auth manage menus"
  on public.menus for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth manage team" on public.team_members;
create policy "auth manage team"
  on public.team_members for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth read checkup" on public.checkup_submissions;
create policy "auth read checkup"
  on public.checkup_submissions for select
  to authenticated
  using (true);

drop policy if exists "anon insert contact" on public.contact_submissions;
create policy "anon insert contact"
  on public.contact_submissions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "auth read contact" on public.contact_submissions;
create policy "auth read contact"
  on public.contact_submissions for select
  to authenticated
  using (true);

-- v3: admin panel — submissions can be deleted by authenticated admins
drop policy if exists "auth delete checkup" on public.checkup_submissions;
create policy "auth delete checkup"
  on public.checkup_submissions for delete
  to authenticated
  using (true);

drop policy if exists "auth delete contact" on public.contact_submissions;
create policy "auth delete contact"
  on public.contact_submissions for delete
  to authenticated
  using (true);

-- v3: case studies + site content
alter table public.case_studies enable row level security;
alter table public.site_content enable row level security;

drop policy if exists "public read case studies" on public.case_studies;
create policy "public read case studies"
  on public.case_studies for select
  to anon, authenticated
  using (true);

drop policy if exists "auth manage case studies" on public.case_studies;
create policy "auth manage case studies"
  on public.case_studies for all
  to authenticated
  using (true) with check (true);

drop policy if exists "public read site content" on public.site_content;
create policy "public read site content"
  on public.site_content for select
  to anon, authenticated
  using (true);

drop policy if exists "auth manage site content" on public.site_content;
create policy "auth manage site content"
  on public.site_content for all
  to authenticated
  using (true) with check (true);

-- ═══ Seed data ═════════════════════════════════════════════════
insert into public.sections (key, name, is_active) values
  ('hero', 'Hero', true),
  ('bento', 'Bento Feature Showcase', true),
  ('services', 'Services Grid', true),
  ('clients', 'Client Logos Marquee', true),
  ('partners', 'Official Partner Badges', true),
  ('team', 'Team Showcase', true),
  ('clocks', 'Live Clocks & Status', true),
  ('checkup_banner', 'Check-Up Banner', true),
  ('cta', 'Final CTA', true)
on conflict (key) do nothing;

-- Seed default menus only on first run (idempotent re-runs)
insert into public.menus (title, url, location, order_index, is_active)
select * from (
  values
    ('Home', '/', 'header', 0, true),
    ('About', '/about', 'header', 1, true),
    ('Services', '/services', 'header', 2, true),
    ('Work', '/work', 'header', 3, true),
    ('Digital Check-Up', '/checkup', 'header', 4, true),
    ('Contact', '/contact', 'header', 5, true),
    ('About', '/about', 'footer', 0, true),
    ('Services', '/services', 'footer', 1, true),
    ('Work', '/work', 'footer', 2, true),
    ('Digital Check-Up', '/checkup', 'footer', 3, true),
    ('Contact', '/contact', 'footer', 4, true),
    ('Instagram', 'https://instagram.com/thisisyoca', 'footer', 5, true),
    ('Email', 'mailto:connect@yoca.net', 'footer', 6, true)
) as seed(title, url, location, order_index, is_active)
where not exists (select 1 from public.menus);

-- team_members intentionally ships without seed rows:
-- add real team members via Supabase Studio or the /admin panel (no fake people).
