-- ═══════════════════════════════════════════════════════════════
-- Yoca — Supabase database schema (Postgres)
-- Run in the Supabase SQL Editor. Includes tables, RLS policies
-- and default seed rows.
-- ═══════════════════════════════════════════════════════════════

-- ── sections: homepage/section visibility switches ─────────────
create table if not exists public.sections (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_sections_touch on public.sections;
create trigger trg_sections_touch
  before update on public.sections
  for each row execute function public.touch_updated_at();

-- ── menus: dynamic header/footer navigation ────────────────────
create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  location text not null check (location in ('header', 'footer')),
  order_index integer not null default 0,
  is_active boolean not null default true
);

create index if not exists idx_menus_location on public.menus (location, order_index);

-- ── team_members: about/team showcase ──────────────────────────
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null default '',
  image_url text,
  linkedin text,
  tags text[] default '{}',
  order_index integer not null default 0,
  is_active boolean not null default true
);

create index if not exists idx_team_order on public.team_members (order_index);

-- ── checkup_submissions: Digital Check-Up leads ────────────────
create table if not exists public.checkup_submissions (
  id uuid primary key default gen_random_uuid(),
  data_json jsonb not null default '{}'::jsonb,
  contact_info_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_checkup_created on public.checkup_submissions (created_at desc);

-- ═══ Row Level Security ════════════════════════════════════════
alter table public.sections enable row level security;
alter table public.menus enable row level security;
alter table public.team_members enable row level security;
alter table public.checkup_submissions enable row level security;

-- Public (anon) read access for content tables
drop policy if exists "public read sections" on public.sections;
create policy "public read sections"
  on public.sections for select
  to anon, authenticated
  using (true);

drop policy if exists "public read menus" on public.menus;
create policy "public read menus"
  on public.menus for select
  to anon, authenticated
  using (true);

drop policy if exists "public read team" on public.team_members;
create policy "public read team"
  on public.team_members for select
  to anon, authenticated
  using (true);

-- Check-up submissions: anonymous INSERT only (no read-back).
-- The admin reads them via the Supabase dashboard or service-role key.
drop policy if exists "anon insert checkup" on public.checkup_submissions;
create policy "anon insert checkup"
  on public.checkup_submissions for insert
  to anon, authenticated
  with check (true);

-- Content management (Supabase Studio / service role bypasses RLS,
-- authenticated dashboard users get full control):
drop policy if exists "auth manage sections" on public.sections;
create policy "auth manage sections"
  on public.sections for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth manage menus" on public.menus;
create policy "auth manage menus"
  on public.menus for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth manage team" on public.team_members;
create policy "auth manage team"
  on public.team_members for all
  to authenticated
  using (true) with check (true);

drop policy if exists "auth read checkup" on public.checkup_submissions;
create policy "auth read checkup"
  on public.checkup_submissions for select
  to authenticated
  using (true);

-- ═══ Seed data ═════════════════════════════════════════════════
insert into public.sections (key, name, is_active) values
  ('hero', 'Hero', true),
  ('bento', 'Bento Feature Showcase', true),
  ('clients', 'Client Logos Marquee', true),
  ('partners', 'Official Partner Badges', true),
  ('team', 'Team Showcase', true),
  ('clocks', 'Live Clocks & Status', true),
  ('checkup_banner', 'Check-Up Banner', true),
  ('cta', 'Final CTA', true)
on conflict (key) do nothing;

-- Seed default menus only on first run (idempotent re-runs)
insert into public.menus (title, url, location, order_index, is_active)
select * from (
  values
    ('Home', '/', 'header', 0, true),
    ('Digital Check-Up', '/checkup', 'header', 1, true),
    ('Contact', 'mailto:connect@yoca.net', 'header', 2, true),
    ('Digital Check-Up', '/checkup', 'footer', 0, true),
    ('Instagram', 'https://instagram.com/thisisyoca', 'footer', 1, true),
    ('Email', 'mailto:connect@yoca.net', 'footer', 2, true)
) as seed(title, url, location, order_index, is_active)
where not exists (select 1 from public.menus);

-- team_members intentionally ships without seed rows:
-- add real team members via Supabase Studio (no fake people).
