-- ═══════════════════════════════════════════════════════════════
-- Yoca — v3 upgrade for EXISTING databases (safe to run repeatedly)
-- Adds: case_studies + site_content tables, admin delete policies,
--        About & Services menu entries.
-- Fresh installs should run schema.sql instead (it includes all this).
-- ═══════════════════════════════════════════════════════════════

-- ── New tables ─────────────────────────────────────────────────
create table if not exists public.case_studies (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  year text not null default '',
  market text not null default '',
  image_url text not null default '',
  services text[] default '{}',
  order_index integer not null default 0,
  is_active boolean not null default true,
  content jsonb not null default '{}'::jsonb
);

create index if not exists idx_case_studies_order on public.case_studies (order_index);

create table if not exists public.site_content (
  id bigint generated by default as identity primary key,
  key text not null,
  locale text not null check (locale in ('en', 'tr', 'az')),
  value text not null default '',
  unique (key, locale)
);

-- ── RLS ────────────────────────────────────────────────────────
alter table public.case_studies enable row level security;
alter table public.site_content enable row level security;

drop policy if exists "public read case studies" on public.case_studies;
create policy "public read case studies"
  on public.case_studies for select
  to anon, authenticated
  using (true);

drop policy if exists "auth manage case studies" on public.case_studies;
create policy "auth manage case studies"
  on public.case_studies for all
  to authenticated
  using (true) with check (true);

drop policy if exists "public read site content" on public.site_content;
create policy "public read site content"
  on public.site_content for select
  to anon, authenticated
  using (true);

drop policy if exists "auth manage site content" on public.site_content;
create policy "auth manage site content"
  on public.site_content for all
  to authenticated
  using (true) with check (true);

-- Admin panel can delete submissions
drop policy if exists "auth delete checkup" on public.checkup_submissions;
create policy "auth delete checkup"
  on public.checkup_submissions for delete
  to authenticated
  using (true);

drop policy if exists "auth delete contact" on public.contact_submissions;
create policy "auth delete contact"
  on public.contact_submissions for delete
  to authenticated
  using (true);

-- ── Menus: add About & Services (header + footer) ──────────────
-- Shift existing header items to make room (only on first run)
update public.menus
  set order_index = order_index + 2
  where location = 'header'
    and url not in ('/', '/about', '/services')
    and not exists (
      select 1 from public.menus where location = 'header' and url = '/about'
    );

insert into public.menus (title, url, location, order_index, is_active)
select 'About', '/about', 'header', 1, true
where not exists (
  select 1 from public.menus where location = 'header' and url = '/about'
);

insert into public.menus (title, url, location, order_index, is_active)
select 'Services', '/services', 'header', 2, true
where not exists (
  select 1 from public.menus where location = 'header' and url = '/services'
);

insert into public.menus (title, url, location, order_index, is_active)
select 'About', '/about', 'footer',
  coalesce((select min(order_index) from public.menus where location = 'footer'), 1) - 2, true
where not exists (
  select 1 from public.menus where location = 'footer' and url = '/about'
);

insert into public.menus (title, url, location, order_index, is_active)
select 'Services', '/services', 'footer',
  coalesce((select min(order_index) from public.menus where location = 'footer' and url <> '/about'), 1) - 1, true
where not exists (
  select 1 from public.menus where location = 'footer' and url = '/services'
);
